version: '3'

services:
  chat-server:
    build:
      context: .
      dockerfile: chatserver/Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - redis
    # Add any necessary environment variables or other configurations here
  subscriber:
    build:
      context: .
      dockerfile: subscriber/Dockerfile
    ports:
      - "9001:9001"
    depends_on:
      - redis
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_data:
    # Add any necessary configurations here